/**
 * Trading OS - Constants
 * Version: v3.0.0-core
 */

const TOS_VERSION = 'v3.1.0-rc.2';

const TOS_SHEETS = {
  HOME: 'HOME',
  DASHBOARD: 'DASHBOARD',
  CONFIG: 'CONFIG',
  MASTER_TRADES: 'MASTER_TRADES',
  TRADE_LEGS: 'TRADE_LEGS',
  RESIDUAL_POSITIONS: 'RESIDUAL_POSITIONS',
  IMPORT_REVIEW: 'IMPORT_REVIEW',
  IGNORED_POSITIONS: 'IGNORED_POSITIONS',
  TRADE_REMOVAL_QUEUE: 'TRADE_REMOVAL_QUEUE',
  ACTION_QUEUE: 'ACTION_QUEUE',
  SYNC_LOG: 'SYNC_LOG',
  QA_REPORT: 'QA_REPORT',
  QA_CHECKLIST: 'QA_CHECKLIST',
  PLAYBOOK: 'PLAYBOOK',
  DDC_MODULE: 'DDC_MODULE',
  CHANGE_LOG: 'CHANGE_LOG'
};

const TOS_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  PARTIAL_EXIT: 'PARTIAL_EXIT',
  COMPLETED_WITH_RESIDUAL: 'COMPLETED_WITH_RESIDUAL',
  CLOSED_PENDING_EXIT_SYNC: 'CLOSED_PENDING_EXIT_SYNC',
  ARCHIVED: 'ARCHIVED',
  IGNORED: 'IGNORED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const TOS_SOURCE = {
  MANUAL: 'MANUAL',
  IBKR: 'IBKR',
  CALCULATED: 'CALCULATED',
  SCANNER: 'SCANNER',
  AI: 'AI'
};



const TOS_PIPELINE_STATUS = {
  STARTED: 'STARTED',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED'
};

const TOS_ERROR_CODE = {
  PIPELINE_ALREADY_RUNNING: 'PIPELINE_ALREADY_RUNNING',
  SNAPSHOT_REQUIRED: 'SNAPSHOT_REQUIRED',
  SNAPSHOT_UNSAFE: 'SNAPSHOT_UNSAFE',
  DEPENDENCY_MISSING: 'DEPENDENCY_MISSING',
  CONFIG_MISSING: 'CONFIG_MISSING',
  PREFLIGHT_FAILED: 'PREFLIGHT_FAILED'
};
const TOS_LOG_STATUS = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARN: 'WARN',
  ERROR: 'ERROR',
  FAIL: 'FAIL'
};
const TOS_ENFORCEMENT = {
  CRITICAL: 'CRITICAL',
  WARNING: 'WARNING',
  INFO: 'INFO'
};
const TOS_IMPORT_DECISION = {
  IMPORT: 'IMPORT',
  IGNORE: 'IGNORE',
  RESIDUAL: 'RESIDUAL',
  ASK_LATER: 'ASK_LATER'
};

const TOS_TRADE_STATUS = {
  DETECTED: 'DETECTED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  IMPORTED: 'IMPORTED',
  OPEN: 'OPEN',
  PARTIAL_CLOSE: 'PARTIAL_CLOSE',
  CLOSED: 'CLOSED',
  PARTIAL_EXIT: 'PARTIAL_EXIT',
  COMPLETED_WITH_RESIDUAL: 'COMPLETED_WITH_RESIDUAL',
  CLOSED_PENDING_EXIT_SYNC: 'CLOSED_PENDING_EXIT_SYNC',
  EXPIRED: 'EXPIRED',
  ARCHIVED: 'ARCHIVED'
};

const TOS_PRIORITY = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

const TOS_CONFIG_DEFAULTS = {
  COMMISSION_PER_LEG: 1.50,
  DEFAULT_RISK_UNIT: 400,
  DEFAULT_STRATEGY: 'DDC'
};