/**
 * Trading OS - Constants
 * Version: v3.0.0-core
 */

const TOS_VERSION = 'v3.0.0-core';

const TOS_SHEETS = {
  HOME: 'HOME',
  DASHBOARD: 'DASHBOARD',
  CONFIG: 'CONFIG',
  MASTER_TRADES: 'MASTER_TRADES',
  TRADE_LEGS: 'TRADE_LEGS',
  IMPORT_REVIEW: 'IMPORT_REVIEW',
  IGNORED_POSITIONS: 'IGNORED_POSITIONS',
  TRADE_REMOVAL_QUEUE: 'TRADE_REMOVAL_QUEUE',
  ACTION_QUEUE: 'ACTION_QUEUE',
  SYNC_LOG: 'SYNC_LOG',
  QA_REPORT: 'QA_REPORT',
  QA_CHECKLIST: 'QA_CHECKLIST',
  PLAYBOOK: 'PLAYBOOK',
  DDC_MODULE: 'DDC_MODULE',
  CHANGE_LOG: 'CHANGE_LOG'
};

const TOS_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  ARCHIVED: 'ARCHIVED',
  IGNORED: 'IGNORED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const TOS_SOURCE = {
  MANUAL: 'MANUAL',
  IBKR: 'IBKR',
  CALCULATED: 'CALCULATED',
  SCANNER: 'SCANNER',
  AI: 'AI'
};

const TOS_LOG_STATUS = {
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARN: 'WARN',
  ERROR: 'ERROR',
  FAIL: 'FAIL'
};
const TOS_ENFORCEMENT = {
  CRITICAL: 'CRITICAL',
  WARNING: 'WARNING',
  INFO: 'INFO'
};
const TOS_IMPORT_DECISION = {
  IMPORT: 'IMPORT',
  IGNORE: 'IGNORE',
  RESIDUAL: 'RESIDUAL',
  ASK_LATER: 'ASK_LATER'
};

const TOS_TRADE_STATUS = {
  DETECTED: 'DETECTED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
  IMPORTED: 'IMPORTED',
  OPEN: 'OPEN',
  PARTIAL_CLOSE: 'PARTIAL_CLOSE',
  CLOSED: 'CLOSED',
  EXPIRED: 'EXPIRED',
  ARCHIVED: 'ARCHIVED'
};

const TOS_PRIORITY = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
};

const TOS_CONFIG_DEFAULTS = {
  COMMISSION_PER_LEG: 1.50,
  DEFAULT_RISK_UNIT: 400,
  DEFAULT_STRATEGY: 'DDC'
};